# Generated by Django 3.1.2 on 2020-10-26 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('enabled', models.BooleanField(default=False, verbose_name='ativar')),
                ('weekdays', models.CharField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], max_length=20, null=True, verbose_name='weekdays')),
                ('period_to', models.DateField(verbose_name='data de término')),
                ('period_from', models.DateField(verbose_name='data de início')),
                ('time_to', models.TimeField(verbose_name='hora de termino')),
                ('time_from', models.TimeField(verbose_name='hora de início')),
                ('institution', models.CharField(max_length=128, verbose_name='instituição')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('job', models.CharField(max_length=128, verbose_name='cargo')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='telefone')),
                ('doc_type', models.CharField(choices=[('RG', 'RG'), ('CPF', 'CPF'), ('USP', 'USP'), ('USP', 'USP'), ('Passaporte', 'Passaporte')], max_length=128, verbose_name='tipo documento')),
                ('doc_number', models.CharField(max_length=128, verbose_name='numero do documento')),
                ('answerable', models.CharField(choices=[('Aswerable1', 'Answerable1'), ('Aswerable2', 'Answerable2')], max_length=128, verbose_name='responsável')),
                ('observation', models.CharField(max_length=1024, verbose_name='observação')),
                ('status', models.CharField(blank=True, choices=[('Autorizado', 'Autorizado'), ('Para autorização', 'Para autorização'), ('Não autorizado', 'Não autorizado')], default='Para autorização', max_length=128, null=True, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de criação')),
                ('created_by', models.CharField(max_length=10, verbose_name='created by')),
            ],
        ),
    ]
